// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpb53JWTuaMFR9rjZt5Y3pEkO23jlVdEA',
    appId: '1:307358521641:web:7b91bf1dd6f2c69e69ff38',
    messagingSenderId: '307358521641',
    projectId: 'patient-care-app-a387a',
    authDomain: 'patient-care-app-a387a.firebaseapp.com',
    storageBucket: 'patient-care-app-a387a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDazyyxO6lZmmimZoNJ8neo1pO2DbO0_w',
    appId: '1:307358521641:android:4a6f1f2ada5d4e7c69ff38',
    messagingSenderId: '307358521641',
    projectId: 'patient-care-app-a387a',
    storageBucket: 'patient-care-app-a387a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNZfGqnm3u-6njAktmC2jltbThdoEYlCQ',
    appId: '1:307358521641:ios:9425506d1ff36a4869ff38',
    messagingSenderId: '307358521641',
    projectId: 'patient-care-app-a387a',
    storageBucket: 'patient-care-app-a387a.appspot.com',
    iosClientId: '307358521641-hpdvo1bvmgtemk954nqp1qnu3rriv6n1.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientcareapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNZfGqnm3u-6njAktmC2jltbThdoEYlCQ',
    appId: '1:307358521641:ios:9425506d1ff36a4869ff38',
    messagingSenderId: '307358521641',
    projectId: 'patient-care-app-a387a',
    storageBucket: 'patient-care-app-a387a.appspot.com',
    iosClientId: '307358521641-hpdvo1bvmgtemk954nqp1qnu3rriv6n1.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientcareapp',
  );
}
